### ISSUE TITLE
Creating new Physical Filesets is Not Idempotent 

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#35]
**Expected Behavior**

Creating a new physical fileset should be idempotent 

**Current Behavior**

When creating a new physical fileset it will create multiple of the same fileset

**Steps to Reproduce**

validated through ansible

```yaml
- rubrik_physical_fileset:
    name: 'AnsibleDemo'
    include: '/usr/local'
    operating_system: 'Linux'
    exclude: '/usr/local/temp,*.mp3,*.mp4,*mp5'
    exclude_exception: '/company*.mp4'
    follow_network_shares: False
    backup_hidden_folders: False
```

**Context**

v1.0.10 of the SDK
