### ISSUE TITLE
Bootstrap Error

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#36]
**Expected Behavior**

Successfully complete a bootstrap.

**Current Behavior**

Bootstrap fails with the below error message.

**Failure Information (for bugs)**

`Error: Error with cluster configuration parameters: java.lang.IllegalArgumentException: requirement failed: Failed to configure IPs for: VREC9A063CC25`

**Steps to Reproduce**

Using a single node cloud cluster and Ansible. This could potentially be an Ansible specific issue but my initial thoughts are that its more SDK related

Ansible Playbook

```yaml
 - rubrik_bootstrap:
        node_ip: "{{ bootstrap_node_ip }}"
        cluster_name: "{{ bootstrap_cluster_name }}"
        admin_email: "{{ bootstrap_admin_email }}"
        admin_password: "{{ bootstrap_admin_password }}"
        management_gateway: "{{ bootstrap_management_gateway }}"
        management_subnet_mask: "{{ bootstrap_management_subnet_mask }}"
        enable_encryption: "{{ bootstrap_enable_encryption }}"
        dns_search_domains: "{{ bootstrap_dns_search_domains }}"
        wait_for_completion: "{{ bootstrap_wait_for_completion }}"
        node_config: "{{ bootstrap_node_config }}"
```

Variables used

```yaml
bootstrap_node_ip: ""
bootstrap_cluster_name: "Ansible Demo"
bootstrap_admin_email: ""
bootstrap_admin_password: ""
bootstrap_management_gateway: ""
bootstrap_management_subnet_mask: ""
bootstrap_enable_encryption: false
bootstrap_dns_search_domains: 
  - "rubrikansible.com"
bootstrap_wait_for_completion: True
bootstrap_node_config: 
    "1": ""
```

**Context**

`rubrik-cdm   1.0.10`
